theme = 'everforest_dark'

[editor]
line-number = 'relative'
mouse = true
true-color = true
color-modes = true
bufferline = 'multiple'

[editor.cursor-shape]
normal = 'block'
insert = 'bar'
select = 'underline'
