[[language]]
name = "c-sharp"
language-servers = ["omnisharp"]

[[language]]
name = "go"

[[language]]
name = "haskell"

[language-server.omnisharp]
command = "/Users/benpl/.omnisharp/OmniSharp"
args = ["--languageserver"]
